# Generated by Django 3.1.7 on 2021-04-07 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210315_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.myuser')),
                ('profile_image', models.ImageField(upload_to='profile_image')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', models.PositiveIntegerField()),
                ('citizenship_number', models.PositiveIntegerField()),
                ('citizenship_front', models.ImageField(upload_to='citizenship')),
                ('citizenship_back', models.ImageField(upload_to='citizenship')),
                ('temp_address', models.CharField(max_length=50)),
                ('per_address', models.CharField(max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
