# Generated by Django 3.1.7 on 2021-04-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20210315_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.myuser')),
                ('name', models.CharField(max_length=100)),
                ('km_driven', models.PositiveSmallIntegerField()),
                ('seat', models.CharField(max_length=100)),
                ('price_per_day', models.CharField(max_length=100)),
                ('wheeler', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('is_available', models.CharField(max_length=100)),
            ],
        ),
    ]
