# Generated by Django 3.1.7 on 2021-04-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20210408_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle',
            field=models.ImageField(upload_to=''),
        ),
    ]
